### PR TITLE
CSM-89: remove duplication and renamed functions

### PR DESCRIPTION
**Pull request by NicholasFolk**
Change-Id: I962fb30dbc27b9085b9b6eab1a1afd72704493cf

### CODE REVIEW

**Comment by k-joseph** [comment]
Looks good, i will be doing some testing and closer review before i can merge this PR

**Comment by dkayiwa** [comment]
@k-joseph should we merge or close this?

**Comment by dkayiwa** [comment]
@k-joseph did you get a chance? :)

**Comment by k-joseph** [comment]
Let me do my best to check it out before the end of this week :-1:

**Comment by dkayiwa** [comment]
@k-joseph did you get a chance? Or should we close it?

**Comment by k-joseph** [comment]
this looks fine @dkayiwa, we can merge this instead of closing it

**Pull request merged**
