### PR TITLE
CSM-94: add order by functionality to chart search

### PR DESCRIPTION
**Pull request by NicholasFolk**
Change-Id: I7ef8c60bc85a361dc871430e047531209374cd07

This is an attempted approach to adding order-by functionality. This currently does not even work at the moment.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@k-joseph any comments to this pull request?

**Comment by k-joseph** [comment]
@dkayiwa this is still incomplete, i hope that @NicholasFolk will work on the remaining part before i can do an overall test of things and we can merge it, checkout the comments on the referenced ticket

**Comment by dkayiwa** [comment]
@NicholasFolk are you actively working on this?

**Comment by k-joseph** [comment]
@dkayiwa this is incomplete and breaks the module's functionality, am closing this PR, we can re-open it if it's updated by @NicholasFolk and when things are working as expected not breaking any of what we already have running well

**Pull request closed without merging**
